version: "3"
volumes:
  db-data:

services:
  app:
    build: .
    volumes:
     - ".:/apps"
    ports:
     - "8000:8000"
    depends_on:
     - db
    links:
     - db
    command: pipenv run start
    tty: true
    stdin_open: true
    #networks:
    # - fpp
    #  sample-net:
    #    ipv4_address: 172.16.10.3
  web:
    image: nginx:1.19.8-alpine
    ports:
     - "80:80"
    depends_on:
     - app
    volumes:
     - "./nginx/conf.d:/etc/nginx/conf.d/"
    # - "./nginx/uwsgi_params:/etc/nginx/uwsgi_params"
    tty: true
    stdin_open: true
    #networks:
    #  sample-net:
    #    ipv4_address: 172.16.10.5
  db:
    image: postgres
    environment:
     - "POSTGRES_USER=postgres"
     - "POSTGRES_PASSWORD=postgres"
    volumes:
     - "db-data:/var/lib/postgresql/data"

#networks:
#  sample-net:
#    driver: bridge
#    ipam:
#      driver: default
#      config:
#       - subnet: 172.16.10.0/24
#       - gateway: 172.16.10.1
