version: "3"

volumes:
  db-data:

services:
  web:
    build: .
    volumes:
     - ".:/apps"
    ports:
     - "80:80"
     - "8000:8000"
    depends_on:
     - db
    links:
     - db
    tty: true
    stdin_open: true
  db:
    image: postgres
    environment:
     - "POSTGRES_USER=postgres"
     - "POSTGRES_PASSWORD=postgres"
    volumes:
     - "db-data:/var/lib/postgresql/data"
