version: "3"

volumes:
  db-data:

services:
  app:
    build: .
    volumes:
     - ".:/apps"
    ports:
     - "8000:8000"
    depends_on:
     - db
    links:
     - db
    command: pipenv run start
    tty: true
    stdin_open: true
  web:
    image: nginx:1.19.8-alpine
    ports:
     - "8080:80"
    depends_on:
     - app
    volumes:
     - "./nginx/cond:/etc/nginx/conf.d"
     - "./nginx/uwsgi_params:/etc/nginx/uwsgi_params"
    tty: true
    stdin_open: true
  db:
    image: postgres
    environment:
     - "POSTGRES_USER=postgres"
     - "POSTGRES_PASSWORD=postgres"
    volumes:
     - "db-data:/var/lib/postgresql/data"
